### PR TITLE
Build multiarch packages

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by jakirkham** [comment]
@marcelotrevisani, would you be able to take a look at this?

**Comment by jakirkham** [comment]
Friendly nudge @marcelotrevisani 😉

**Comment by marcelotrevisani** [comment]
> Friendly nudge @marcelotrevisani

Sorry for my delay @jakirkham , if I take more than a couple days to answer you please feel free to ping me again.

It looks good to me! I will merge it! Thanks!

**Comment by jakirkham** [comment]
Thanks Marcelo! 😄

**Pull request merged**
